FROM ruby:latest
ENV DEBIAN_FRONTEND noninteractive

LABEL maintainer="Watcharapong Wongkaew"

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    locales \
    imagemagick \
    build-essential \
    zlib1g-dev \
    jupyter-nbconvert \
    inotify-tools procps && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/*

RUN sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen && \
    locale-gen

ENV LANG=en_US.UTF-8 \
    LANGUAGE=en_US:en \
    LC_ALL=en_US.UTF-8 \
    JEKYLL_ENV=production

RUN mkdir /srv/jekyll

WORKDIR /srv/jekyll

# install jekyll and dependencies
RUN gem install jekyll bundler

EXPOSE 8080

# Use a direct command instead of an entry point script
CMD /bin/bash -c "bundle install && jekyll serve --watch --port=8080 --host=0.0.0.0 --livereload --verbose --trace --force_polling"
